# 80 scales (48 scales +16 drums +16 keyboard) – Group 1-16, Auto 17-32, Lock 33-48, PadMode+Pad 49-64 – Group 1-16, Auto 17-32, Lock 33-48
client_name = "Maschine Mikro MK3"
port_name = "Maschine Mikro MK3 MIDI Out"

midi_channel = 0
pad_channel = 9

pad_pages = [
  # Chromatic
  [36, 37, 38, 39, 32, 33, 34, 35, 28, 29, 30, 31, 24, 25, 26, 27],
  # Major
  [45, 47, 48, 50, 38, 40, 41, 43, 31, 33, 35, 36, 24, 26, 28, 29],
  # Dorian
  [45, 46, 48, 50, 38, 39, 41, 43, 31, 33, 34, 36, 24, 26, 27, 29],
  # Phrygian
  [44, 46, 48, 49, 37, 39, 41, 43, 31, 32, 34, 36, 24, 25, 27, 29],
  # Lydian
  [45, 47, 48, 50, 38, 40, 42, 43, 31, 33, 35, 36, 24, 26, 28, 30],
  # Mixolydian
  [45, 46, 48, 50, 38, 40, 41, 43, 31, 33, 34, 36, 24, 26, 28, 29],
  # Natural Minor
  [44, 46, 48, 50, 38, 39, 41, 43, 31, 32, 34, 36, 24, 26, 27, 29],
  # Locrian
  [44, 46, 48, 49, 37, 39, 41, 42, 30, 32, 34, 36, 24, 25, 27, 29],
  # Harmonic Minor
  [44, 47, 48, 50, 38, 39, 41, 43, 31, 32, 35, 36, 24, 26, 27, 29],
  # Melodic Minor
  [45, 47, 48, 50, 38, 39, 41, 43, 31, 33, 35, 36, 24, 26, 27, 29],
  # Harmonic Major
  [44, 47, 48, 50, 38, 40, 41, 43, 31, 32, 35, 36, 24, 26, 28, 29],
  # Phrygian Dominant
  [44, 46, 48, 49, 37, 40, 41, 43, 31, 32, 34, 36, 24, 25, 28, 29],
  # Mixolydian b6
  [44, 46, 48, 50, 38, 40, 41, 43, 31, 32, 34, 36, 24, 26, 28, 29],
  # Major Pentatonic
  [52, 55, 57, 60, 43, 45, 48, 50, 33, 36, 38, 40, 24, 26, 28, 31],
  # Minor Pentatonic
  [53, 55, 58, 60, 43, 46, 48, 51, 34, 36, 39, 41, 24, 27, 29, 31],
  # Major Blues
  [48, 50, 51, 52, 39, 40, 43, 45, 31, 33, 36, 38, 24, 26, 27, 28],
  # Minor Blues
  [48, 51, 53, 54, 41, 42, 43, 46, 31, 34, 36, 39, 24, 27, 29, 30],
  # Double Harmonic Major
  [44, 47, 48, 49, 37, 40, 41, 43, 31, 32, 35, 36, 24, 25, 28, 29],
  # Neapolitan Minor
  [44, 47, 48, 49, 37, 39, 41, 43, 31, 32, 35, 36, 24, 25, 27, 29],
  # Neapolitan Major
  [45, 47, 48, 49, 37, 40, 41, 43, 31, 33, 35, 36, 24, 25, 28, 29],
  # Hungarian Minor
  [44, 47, 48, 50, 38, 39, 42, 43, 31, 32, 35, 36, 24, 26, 27, 30],
  # Hungarian Major
  [45, 46, 48, 51, 39, 40, 42, 43, 31, 33, 34, 36, 24, 27, 28, 30],
  # Persian
  [44, 47, 48, 49, 37, 40, 41, 42, 30, 32, 35, 36, 24, 25, 28, 29],
  # Ukrainian Dorian
  [45, 46, 48, 50, 38, 39, 42, 43, 31, 33, 34, 36, 24, 26, 27, 30],
  # Hirajoshi
  [51, 55, 56, 60, 43, 44, 48, 50, 32, 36, 38, 39, 24, 26, 27, 31],
  # In Sen
  [53, 55, 58, 60, 43, 46, 48, 49, 34, 36, 37, 41, 24, 25, 29, 31],
  # Iwato
  [53, 54, 58, 60, 42, 46, 48, 49, 34, 36, 37, 41, 24, 25, 29, 30],
  # Kumoi
  [51, 55, 57, 60, 43, 45, 48, 50, 33, 36, 38, 39, 24, 26, 27, 31],
  # Yo
  [53, 55, 57, 60, 43, 45, 48, 50, 33, 36, 38, 41, 24, 26, 29, 31],
  # Egyptian
  [53, 55, 58, 60, 43, 46, 48, 50, 34, 36, 38, 41, 24, 26, 29, 31],
  # Japanese Ritsu
  [53, 55, 57, 60, 43, 45, 48, 50, 33, 36, 38, 41, 24, 26, 29, 31],
  # Japanese Akebono
  [51, 55, 56, 60, 43, 44, 48, 50, 32, 36, 38, 39, 24, 26, 27, 31],
  # Japanese Sakura
  [53, 55, 56, 60, 43, 44, 48, 49, 32, 36, 37, 41, 24, 25, 29, 31],
  # Japanese Miyako-bushi
  [51, 55, 56, 60, 43, 44, 48, 49, 32, 36, 37, 39, 24, 25, 27, 31],
  # Bhairav
  [44, 47, 48, 49, 37, 40, 41, 43, 31, 32, 35, 36, 24, 25, 28, 29],
  # Todi
  [44, 47, 48, 49, 37, 39, 42, 43, 31, 32, 35, 36, 24, 25, 27, 30],
  # Marwa
  [45, 47, 48, 49, 37, 40, 42, 43, 31, 33, 35, 36, 24, 25, 28, 30],
  # Kafi
  [45, 46, 48, 50, 38, 39, 41, 43, 31, 33, 34, 36, 24, 26, 27, 29],
  # Hijaz
  [44, 46, 48, 49, 37, 40, 41, 43, 31, 32, 34, 36, 24, 25, 28, 29],
  # Bayati
  [44, 46, 48, 49, 37, 39, 41, 43, 31, 32, 34, 36, 24, 25, 27, 29],
  # Nahawand
  [44, 47, 48, 50, 38, 39, 41, 43, 31, 32, 35, 36, 24, 26, 27, 29],
  # Chinese Shang
  [45, 46, 48, 50, 38, 39, 41, 43, 31, 33, 34, 36, 24, 26, 27, 29],
  # Chinese Yu
  [53, 55, 58, 60, 43, 46, 48, 51, 34, 36, 39, 41, 24, 27, 29, 31],
  # Pelog
  [51, 55, 56, 60, 43, 44, 48, 49, 32, 36, 37, 39, 24, 25, 27, 31],
  # Slendro
  [53, 55, 58, 60, 43, 46, 48, 50, 34, 36, 38, 41, 24, 26, 29, 31],
  # Byzantine
  [44, 47, 48, 49, 37, 40, 41, 43, 31, 32, 35, 36, 24, 25, 28, 29],
  # Prometheus
  [48, 50, 52, 54, 40, 42, 45, 46, 33, 34, 36, 38, 24, 26, 28, 30],
  # Romanian Minor
  [45, 46, 48, 50, 38, 39, 42, 43, 31, 33, 34, 36, 24, 26, 27, 30],
  # Drums 1
  [36, 38, 42, 46, 41, 43, 45, 47, 37, 39, 44, 49, 51, 54, 56, 59],
  # Drums 2
  [38, 40, 44, 48, 43, 45, 47, 49, 39, 41, 46, 51, 53, 56, 58, 61],
  # Drums 3
  [40, 42, 46, 50, 45, 47, 49, 51, 41, 43, 48, 53, 55, 58, 60, 63],
  # Drums 4
  [42, 44, 48, 52, 47, 49, 51, 53, 43, 45, 50, 55, 57, 60, 62, 65],
  # Drums 5
  [44, 46, 50, 54, 49, 51, 53, 55, 45, 47, 52, 57, 59, 62, 64, 67],
  # Drums 6
  [46, 48, 52, 56, 51, 53, 55, 57, 47, 49, 54, 59, 61, 64, 66, 69],
  # Drums 7
  [48, 50, 54, 58, 53, 55, 57, 59, 49, 51, 56, 61, 63, 66, 68, 71],
  # Drums 8
  [50, 52, 56, 60, 55, 57, 59, 61, 51, 53, 58, 63, 65, 68, 70, 73],
  # Drums 9
  [52, 54, 58, 62, 57, 59, 61, 63, 53, 55, 60, 65, 67, 70, 72, 75],
  # Drums 10
  [54, 56, 60, 64, 59, 61, 63, 65, 55, 57, 62, 67, 69, 72, 74, 77],
  # Drums 11
  [56, 58, 62, 66, 61, 63, 65, 67, 57, 59, 64, 69, 71, 74, 76, 79],
  # Drums 12
  [58, 60, 64, 68, 63, 65, 67, 69, 59, 61, 66, 71, 73, 76, 78, 81],
  # Drums 13
  [60, 62, 66, 70, 65, 67, 69, 71, 61, 63, 68, 73, 75, 78, 80, 83],
  # Drums 14
  [62, 64, 68, 72, 67, 69, 71, 73, 63, 65, 70, 75, 77, 80, 82, 85],
  # Drums 15
  [64, 66, 70, 74, 69, 71, 73, 75, 65, 67, 72, 77, 79, 82, 84, 87],
  # Drums 16
  [66, 68, 72, 76, 71, 73, 75, 77, 67, 69, 74, 79, 81, 84, 86, 89],
  # Keyboard Major Blues
  [48, 50, 51, 52, 39, 40, 43, 45, 31, 33, 36, 38, 24, 26, 27, 28],
  # Keyboard Bebop
  [43, 45, 46, 47, 36, 38, 40, 41, 31, 33, 34, 35, 24, 26, 28, 29],
  # Keyboard Diminished
  [42, 44, 45, 47, 36, 38, 39, 41, 30, 32, 33, 35, 24, 26, 27, 29],
  # Keyboard Lydian Dominant
  [45, 46, 48, 50, 38, 40, 42, 43, 31, 33, 34, 36, 24, 26, 28, 30],
  # Keyboard Altered
  [44, 46, 48, 49, 37, 39, 40, 42, 30, 32, 34, 36, 24, 25, 27, 28],
  # Keyboard Dorian b2
  [45, 46, 48, 49, 37, 39, 41, 43, 31, 33, 34, 36, 24, 25, 27, 29],
  # Keyboard Ultralocrian
  [44, 45, 48, 49, 37, 39, 40, 42, 30, 32, 33, 36, 24, 25, 27, 28],
  # Keyboard Augmented Heptatonic
  [44, 47, 48, 51, 39, 40, 41, 43, 31, 32, 35, 36, 24, 27, 28, 29],
  # Keyboard Whole Tone
  [48, 50, 52, 54, 40, 42, 44, 46, 32, 34, 36, 38, 24, 26, 28, 30],
  # Keyboard Locrian Major
  [44, 46, 48, 50, 38, 40, 41, 42, 30, 32, 34, 36, 24, 26, 28, 29],
  # Keyboard Double Harmonic Lydian
  [44, 47, 48, 49, 37, 40, 42, 43, 31, 32, 35, 36, 24, 25, 28, 30],
  # Keyboard Enigmatic
  [46, 47, 48, 49, 37, 40, 42, 44, 32, 34, 35, 36, 24, 25, 28, 30],
  # Keyboard Major Augmented
  [45, 47, 48, 50, 38, 40, 41, 44, 32, 33, 35, 36, 24, 26, 28, 29],
  # Keyboard Messiaen #4
  [42, 43, 44, 47, 36, 37, 38, 41, 30, 31, 32, 35, 24, 25, 26, 29],
  # Keyboard Composite Blues
  [40, 41, 42, 43, 34, 36, 38, 39, 29, 30, 31, 33, 24, 26, 27, 28],
  # Keyboard Lydian Augmented
  [45, 47, 48, 50, 38, 40, 42, 44, 32, 33, 35, 36, 24, 26, 28, 30],
]

pad_page_button = "Group"
auto_page_button = "Auto"
lock_page_button = "Lock"
pad_page_hold_select = true
pad_aftertouch = "poly"
daw_mackie = false

scale_names = ['Chromatic', 'Major', 'Dorian', 'Phrygian', 'Lydian', 'Mixolydian', 'Natural Minor', 'Locrian', 'Harmonic Minor', 'Melodic Minor', 'Harmonic Major', 'Phrygian Dominant', 'Mixolydian b6', 'Major Pentatonic', 'Minor Pentatonic', 'Major Blues', 'Minor Blues', 'Double Harmonic Major', 'Neapolitan Minor', 'Neapolitan Major', 'Hungarian Minor', 'Hungarian Major', 'Persian', 'Ukrainian Dorian', 'Hirajoshi', 'In Sen', 'Iwato', 'Kumoi', 'Yo', 'Egyptian', 'Japanese Ritsu', 'Japanese Akebono', 'Japanese Sakura', 'Japanese Miyako-bushi', 'Bhairav', 'Todi', 'Marwa', 'Kafi', 'Hijaz', 'Bayati', 'Nahawand', 'Chinese Shang', 'Chinese Yu', 'Pelog', 'Slendro', 'Byzantine', 'Prometheus', 'Romanian Minor', 'Drums 1', 'Drums 2', 'Drums 3', 'Drums 4', 'Drums 5', 'Drums 6', 'Drums 7', 'Drums 8', 'Drums 9', 'Drums 10', 'Drums 11', 'Drums 12', 'Drums 13', 'Drums 14', 'Drums 15', 'Drums 16', 'Major Blues Kbd', 'Bebop Kbd', 'Diminished Kbd', 'Lydian Dominant Kbd', 'Altered Kbd', 'Dorian b2 Kbd', 'Ultralocrian Kbd', 'Augmented Heptatonic Kbd', 'Whole Tone Kbd', 'Locrian Major Kbd', 'Double Harmonic Lydian Kbd', 'Enigmatic Kbd', 'Major Augmented Kbd', 'Messiaen #4 Kbd', 'Composite Blues Kbd', 'Lydian Augmented Kbd']
pad_page_colors = ['Red', 'Orange', 'LightOrange', 'WarmYellow', 'Yellow', 'Lime', 'Green', 'Mint', 'Cyan', 'Turquoise', 'Blue', 'Plum', 'Violet', 'Purple', 'Magenta', 'Fuchsia', 'White', 'Red', 'Orange', 'LightOrange', 'WarmYellow', 'Yellow', 'Lime', 'Green', 'Mint', 'Cyan', 'Turquoise', 'Blue', 'Plum', 'Violet', 'Purple', 'Magenta', 'Fuchsia', 'White', 'Red', 'Orange', 'LightOrange', 'WarmYellow', 'Yellow', 'Lime', 'Green', 'Mint', 'Cyan', 'Turquoise', 'Blue', 'Plum', 'Violet', 'Purple', 'White', 'White', 'White', 'White', 'White', 'White', 'White', 'White', 'White', 'White', 'White', 'White', 'White', 'White', 'White', 'White', 'Plum', 'Violet', 'Purple', 'Magenta', 'Fuchsia', 'White', 'Red', 'Orange', 'LightOrange', 'WarmYellow', 'Yellow', 'Lime', 'Green', 'Mint', 'Cyan', 'Turquoise']

[chord_types]
"Chromatic" = "power"
"Minor Pentatonic" = "power"
"Minor Blues" = "power"
"Hirajoshi" = "power"
"In Sen" = "power"
"Iwato" = "power"
"Pelog" = "power"
"Slendro" = "power"
"Chinese Yu" = "power"
"Major Pentatonic" = "power"
"Major Blues" = "power"
"Japanese Ritsu" = "power"
"Japanese Akebono" = "power"
"Japanese Sakura" = "power"
"Japanese Miyako-bushi" = "power"
"Egyptian" = "power"
"Kumoi" = "power"
"Yo" = "power"

[transpose]
semitone_up = "Right"
semitone_down = "Left"
octave_up = ""
octave_down = ""
reset = ""

[encoder]
cc = 7
type = "cc"
mode = "relative"

[slider]
cc = 1
type = "cc"
mode = "absolute"

[buttons]
Auto = { type = "cc", cc = 35 }
Browse = { type = "cc", cc = 40 }
Chords = { type = "cc", cc = 84 }
Duplicate = { type = "cc", cc = 89 }
EncoderPress = { type = "cc", cc = 8 }
Erase = { type = "cc", cc = 54 }
Events = { type = "cc", cc = 87 }
FixedVol = { type = "cc", cc = 80 }
Follow = { type = "cc", cc = 56 }
Group = { type = "cc", cc = 34 }
Keyboard = { type = "cc", cc = 82 }
Lock = { type = "cc", cc = 36 }
Maschine = { type = "cc", cc = 38 }
Mod = { type = "cc", cc = 50 }
Mute = { type = "cc", cc = 92 }
NoteRepeat = { type = "cc", cc = 37 }
Notes = { type = "cc", cc = 52 }
PadMode = { type = "cc", cc = 81 }
Pattern = { type = "cc", cc = 86 }
Perform = { type = "cc", cc = 51 }
Pitch = { type = "cc", cc = 49 }
Play = { type = "cc", cc = 57 }
Plugin = { type = "cc", cc = 45 }
Rec = { type = "cc", cc = 58 }
Restart = { type = "cc", cc = 53 }
Sampling = { type = "cc", cc = 47 }
Scene = { type = "cc", cc = 85 }
Select = { type = "cc", cc = 90 }
Solo = { type = "cc", cc = 91 }
Star = { type = "cc", cc = 39 }
Step = { type = "cc", cc = 83 }
Stop = { type = "cc", cc = 59 }
Swing = { type = "cc", cc = 46 }
Tap = { type = "cc", cc = 55 }
Tempo = { type = "cc", cc = 48 }
Variation = { type = "cc", cc = 88 }
Volume = { type = "cc", cc = 44 }
